# Generated by Django 4.0.4 on 2022-12-28 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0085_customer_date_first'),
        ('salesreport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=12, null=True)),
                ('type', models.CharField(max_length=30)),
                ('region', models.CharField(default='77', max_length=2)),
                ('group', models.CharField(max_length=255)),
                ('frigat_id', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(max_length=255)),
                ('all_phones', models.CharField(max_length=255, null=True)),
                ('mail', models.CharField(max_length=255, null=True)),
                ('all_mails', models.CharField(max_length=255, null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('our_manager', models.CharField(max_length=255)),
                ('customer_group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.customer_groups')),
                ('customer_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.customer_types')),
            ],
        ),
    ]
