# Generated by Django 4.0.4 on 2022-12-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0002_customer_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_all',
            name='date_import',
            field=models.DateField(default='2010-01-01'),
        ),
    ]
