# Generated by Django 4.0.4 on 2022-12-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0003_customer_all_date_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_all',
            name='region',
            field=models.CharField(max_length=2),
        ),
    ]
