# Generated by Django 4.0.4 on 2022-12-30 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0085_customer_date_first'),
        ('salesreport', '0006_alter_customer_all_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_all',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.customer'),
        ),
    ]
