# Generated by Django 4.0.4 on 2022-12-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0008_remove_sales_docs_customer_sales_sales_docs_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_all',
        ),
    ]
