# Generated by Django 4.0.4 on 2023-01-03 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0088_customer_groups_mail_customer_groups_phone'),
        ('salesreport', '0009_delete_customer_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_doc_imports',
            name='code_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.customer'),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='customer_all',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.customer_all'),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='customer_frigat_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='customer_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='good_group',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='good_group_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='good_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='good_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='good_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='sales_doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesreport.sales_docs'),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='sales_doc_date',
            field=models.DateField(default='2010-01-01'),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='sales_doc_name',
            field=models.CharField(default='Расходная накладная', max_length=255),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='sales_doc_no',
            field=models.IntegerField(null=True),
        ),
    ]
