# Generated by Django 4.0.4 on 2023-01-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0010_sales_doc_imports_code_1_sales_doc_imports_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_doc_imports',
            name='main_color',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
