# Generated by Django 4.0.4 on 2023-01-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0012_sales_doc_imports_import_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_doc_imports',
            name='buy_with_vat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='buy_without_vat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='sale_price_vat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='sale_with_vat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='sale_without_vat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales_doc_imports',
            name='sales_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
