# Generated by Django 4.0.4 on 2023-01-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0013_sales_doc_imports_buy_with_vat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_doc_imports',
            name='color_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
