# Generated by Django 4.0.4 on 2023-01-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0015_sales_docs_quantity_sales_docs_total_buy_with_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_docs',
            name='sales_doc_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='sales_docs',
            name='sales_doc_number',
            field=models.IntegerField(null=True),
        ),
    ]
