# Generated by Django 4.0.4 on 2023-01-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0016_sales_docs_sales_doc_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_docs',
            name='sales_doc_date',
            field=models.DateField(default='1999-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='sales_docs',
            name='sales_doc_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
