# Generated by Django 4.0.4 on 2023-01-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0017_alter_sales_docs_sales_doc_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_docs',
            name='sales_doc_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='sales_docs',
            name='sales_doc_number',
            field=models.IntegerField(default=0),
        ),
    ]
