# Generated by Django 4.0.4 on 2023-01-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0019_sales_docs_good_no_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_docs',
            name='eco',
            field=models.BooleanField(default=True),
        ),
    ]
