# Generated by Django 4.0.4 on 2023-01-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0020_sales_docs_eco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_doc_imports',
            name='code_1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
