# Generated by Django 4.0.4 on 2023-01-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0021_alter_sales_doc_imports_code_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_doc_imports',
            name='sales_doc_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sales_docs',
            name='sales_doc_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
