# Generated by Django 4.0.4 on 2023-01-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0023_alter_sales_doc_imports_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_doc_imports',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
