# Generated by Django 4.0.4 on 2023-01-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0024_alter_sales_doc_imports_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_doc_imports',
            name='main_color',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
