# Generated by Django 4.0.4 on 2023-02-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0026_remove_sales_doc_imports_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_doc_imports',
            name='color_code',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
