# Generated by Django 4.0.4 on 2023-03-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0028_reportperiod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales_docs',
            options={'verbose_name': 'отгрузочные документы'},
        ),
        migrations.AddField(
            model_name='sales_docs',
            name='month',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month', to='salesreport.reportperiod'),
        ),
        migrations.AddField(
            model_name='sales_docs',
            name='quarter',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarter', to='salesreport.reportperiod'),
        ),
        migrations.AddField(
            model_name='sales_docs',
            name='week',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='week', to='salesreport.reportperiod'),
        ),
        migrations.AddField(
            model_name='sales_docs',
            name='year',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='year', to='salesreport.reportperiod'),
        ),
    ]
