# Generated by Django 4.0.4 on 2023-03-05 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0098_alter_customer_all_date_last'),
        ('salesreport', '0032_customerperiodsmonth_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerperiodsmonth',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.customer_groups'),
        ),
        migrations.AddField(
            model_name='customerperiodsmonth',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerperiodsquarter',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.customer_groups'),
        ),
        migrations.AddField(
            model_name='customerperiodsquarter',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerperiodsweek',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.customer_groups'),
        ),
        migrations.AddField(
            model_name='customerperiodsweek',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerperiodsyear',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.customer_groups'),
        ),
        migrations.AddField(
            model_name='customerperiodsyear',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
