# Generated by Django 4.0.4 on 2023-03-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0033_customerperiodsmonth_group_customerperiodsmonth_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerperiodsmonth',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerperiodsquarter',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerperiodsweek',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerperiodsyear',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=100, null=True),
        ),
    ]
