# Generated by Django 4.0.4 on 2023-03-07 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0034_alter_customerperiodsmonth_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerperiodsmonth',
            old_name='sales_eco_with_vat',
            new_name='sales_with_vat_eco',
        ),
        migrations.RenameField(
            model_name='customerperiodsmonth',
            old_name='sales_no_eco_with_vat',
            new_name='sales_with_vat_no_eco',
        ),
        migrations.RenameField(
            model_name='customerperiodsquarter',
            old_name='sales_eco_with_vat',
            new_name='sales_with_vat_eco',
        ),
        migrations.RenameField(
            model_name='customerperiodsquarter',
            old_name='sales_no_eco_with_vat',
            new_name='sales_with_vat_no_eco',
        ),
        migrations.RenameField(
            model_name='customerperiodsweek',
            old_name='sales_eco_with_vat',
            new_name='sales_with_vat_eco',
        ),
        migrations.RenameField(
            model_name='customerperiodsweek',
            old_name='sales_no_eco_with_vat',
            new_name='sales_with_vat_no_eco',
        ),
        migrations.RenameField(
            model_name='customerperiodsyear',
            old_name='sales_eco_with_vat',
            new_name='sales_with_vat_eco',
        ),
        migrations.RenameField(
            model_name='customerperiodsyear',
            old_name='sales_no_eco_with_vat',
            new_name='sales_with_vat_no_eco',
        ),
    ]
