from salesreport.views.main import *
from salesreport.views.unsinchronized import *
from salesreport.views.customer import *
from salesreport.views.customer_all import *
from salesreport.views.group import *
from salesreport.views.admin import *
from salesreport.views.management import *
from salesreport.views.exra_reports import *
from salesreport.views.report_customer_period import *
