# Generated by Django 4.0.4 on 2022-05-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color_scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Detail_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail1', models.SmallIntegerField(default=1)),
                ('detail1_name', models.CharField(max_length=60)),
                ('detail2', models.SmallIntegerField(default=0)),
                ('detail2_name', models.CharField(max_length=60)),
                ('detail3', models.SmallIntegerField(default=0)),
                ('detail3_name', models.CharField(max_length=60)),
                ('detail4', models.SmallIntegerField(default=0)),
                ('detail4_name', models.CharField(max_length=60)),
                ('detail5', models.SmallIntegerField(default=0)),
                ('detail5_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=6)),
                ('color_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.color_scheme')),
                ('details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.detail_set')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date of order')),
                ('date_num', models.CharField(max_length=6)),
                ('order_number', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Print_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_name', models.CharField(max_length=20)),
                ('place_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Print_position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_option', models.CharField(max_length=20)),
                ('position_orientation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Print_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_color', models.CharField(max_length=10)),
                ('detail1_color', models.CharField(max_length=10)),
                ('detail2_color', models.CharField(max_length=10)),
                ('detail3_color', models.CharField(max_length=10)),
                ('detail4_color', models.CharField(max_length=10)),
                ('detail5_color', models.CharField(max_length=10)),
                ('item_quant', models.IntegerField(default=1)),
                ('print_name', models.CharField(max_length=40)),
                ('item_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket.items')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket.order')),
            ],
        ),
        migrations.CreateModel(
            name='Order_item_print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('shots', models.SmallIntegerField(default=1)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket.order_items')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.print_place')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.print_position')),
            ],
        ),
        migrations.CreateModel(
            name='Item_to_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket.items')),
                ('print_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket.print_type')),
            ],
        ),
        migrations.CreateModel(
            name='Item_to_position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket.items')),
                ('position_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket.print_position')),
            ],
        ),
        migrations.CreateModel(
            name='Item_to_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket.items')),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket.print_place')),
            ],
        ),
        migrations.CreateModel(
            name='Item_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.CharField(max_length=60)),
                ('color_name', models.CharField(max_length=10)),
                ('color_code', models.CharField(max_length=7)),
                ('color_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.color_scheme')),
            ],
        ),
        migrations.AddField(
            model_name='detail_set',
            name='detail1_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail1', to='maket.print_place'),
        ),
        migrations.AddField(
            model_name='detail_set',
            name='detail2_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail2', to='maket.print_place'),
        ),
        migrations.AddField(
            model_name='detail_set',
            name='detail3_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail3', to='maket.print_place'),
        ),
        migrations.AddField(
            model_name='detail_set',
            name='detail4_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail4', to='maket.print_place'),
        ),
        migrations.AddField(
            model_name='detail_set',
            name='detail5_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail5', to='maket.print_place'),
        ),
    ]
