# Generated by Django 4.0.4 on 2022-05-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='company',
            new_name='group',
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(default='77', max_length=2),
        ),
        migrations.AlterField(
            model_name='detail_set',
            name='detail1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='detail_set',
            name='detail2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detail_set',
            name='detail3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detail_set',
            name='detail4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detail_set',
            name='detail5',
            field=models.BooleanField(default=False),
        ),
    ]
