# Generated by Django 4.0.4 on 2022-05-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0003_alter_color_scheme_scheme_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print_place',
            name='place_name',
            field=models.CharField(max_length=30),
        ),
    ]
