# Generated by Django 4.0.4 on 2022-07-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0007_item_imports_print_id_print_imports_print_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_imports',
            name='print_id',
        ),
        migrations.RemoveField(
            model_name='print_imports',
            name='print_id',
        ),
    ]
