# Generated by Django 4.0.4 on 2022-07-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0009_item_imports_print_id_print_imports_print_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_imports',
            name='order_date',
            field=models.DateField(default='1000-01-01'),
        ),
        migrations.AlterField(
            model_name='item_imports',
            name='print_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='print_imports',
            name='print_id',
            field=models.IntegerField(default=0),
        ),
    ]
