# Generated by Django 4.0.4 on 2022-07-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0010_order_imports_order_date_alter_item_imports_print_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_imports',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
