# Generated by Django 4.0.4 on 2022-07-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0011_item_imports_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='print_imports',
            name='colors',
            field=models.SmallIntegerField(default=1),
        ),
    ]
