# Generated by Django 4.0.4 on 2022-07-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0012_print_imports_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print_imports',
            name='place',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
