# Generated by Django 4.0.4 on 2022-07-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0013_alter_print_imports_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_imports',
            name='customer',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
