# Generated by Django 4.0.4 on 2022-07-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0015_rename_customer_order_imports_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_imports',
            name='detail1_color',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item_imports',
            name='detail2_color',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item_imports',
            name='detail3_color',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item_imports',
            name='detail4_color',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item_imports',
            name='detail5_color',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item_imports',
            name='item_color',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
