# Generated by Django 4.0.4 on 2022-07-13 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0016_alter_item_imports_detail1_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='inn',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='order_imports',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.customer'),
        ),
        migrations.AddField(
            model_name='order_imports',
            name='date_num',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='item_color',
            name='color_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='item_color',
            name='color_name',
            field=models.CharField(max_length=60),
        ),
    ]
