# Generated by Django 4.0.4 on 2022-07-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0018_detail_set_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_imports',
            name='item_group',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
