# Generated by Django 4.0.4 on 2022-07-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0019_item_imports_item_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_imports',
            name='item_group',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
    ]
