# Generated by Django 4.0.4 on 2022-07-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0020_alter_item_imports_item_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_set',
            name='detail2_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='detail_set',
            name='detail3_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='detail_set',
            name='detail4_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='detail_set',
            name='detail5_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
