# Generated by Django 4.0.4 on 2022-07-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0021_alter_detail_set_detail2_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_set',
            name='detail2_name',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='detail_set',
            name='detail3_name',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='detail_set',
            name='detail4_name',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='detail_set',
            name='detail5_name',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
