# Generated by Django 4.0.4 on 2022-07-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0025_alter_detail_set_detail1_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_set',
            name='detail4_place',
            field=models.BooleanField(default=False),
        ),
    ]
