# Generated by Django 4.0.4 on 2022-07-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0026_alter_detail_set_detail4_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_to_position',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='item_to_position',
            name='position_name',
        ),
        migrations.RemoveField(
            model_name='item_to_type',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='item_to_type',
            name='print_type',
        ),
        migrations.RemoveField(
            model_name='items',
            name='color_scheme',
        ),
        migrations.RemoveField(
            model_name='items',
            name='details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='item_series',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='order',
        ),
        migrations.AddField(
            model_name='detail_set',
            name='color_scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.color_scheme'),
        ),
        migrations.AddField(
            model_name='detail_set',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order_item_print',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket.item_imports'),
        ),
        migrations.DeleteModel(
            name='Item_to_color',
        ),
        migrations.DeleteModel(
            name='Item_to_position',
        ),
        migrations.DeleteModel(
            name='Item_to_type',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_items',
        ),
    ]
