# Generated by Django 4.0.4 on 2022-07-16 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0027_remove_item_to_position_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_set',
            name='detail1',
        ),
        migrations.RemoveField(
            model_name='detail_set',
            name='detail2',
        ),
        migrations.RemoveField(
            model_name='detail_set',
            name='detail3',
        ),
        migrations.RemoveField(
            model_name='detail_set',
            name='detail4',
        ),
        migrations.RemoveField(
            model_name='detail_set',
            name='detail5',
        ),
        migrations.AddField(
            model_name='item_imports',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.detail_set'),
        ),
    ]
