# Generated by Django 4.0.4 on 2022-07-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0029_alter_order_imports_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_color',
            name='pantone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
