# Generated by Django 4.0.4 on 2022-07-19 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0031_alter_item_color_pantone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField(default=0, max_length=3)),
                ('date', models.DateField(default='')),
                ('format', models.CharField(default='A5', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='order_imports',
            name='film',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.films'),
        ),
    ]
