# Generated by Django 4.0.4 on 2022-07-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0033_order_imports_film_status_alter_films_film_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_imports',
            name='customer_manager',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order_imports',
            name='customer_manager_mail',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order_imports',
            name='customer_manager_phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order_imports',
            name='order_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_imports',
            name='order_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order_imports',
            name='our_manager',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
