# Generated by Django 4.0.4 on 2022-07-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0034_order_imports_customer_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print_imports',
            name='position',
        ),
        migrations.AddField(
            model_name='item_imports',
            name='item_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='print_imports',
            name='print_price',
            field=models.FloatField(default=0),
        ),
    ]
