# Generated by Django 4.0.4 on 2022-07-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0036_alter_detail_set_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_imports',
            name='num_prints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item_imports',
            name='print_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order_imports',
            name='print_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_imports',
            name='print_sum',
            field=models.FloatField(default=0),
        ),
    ]
