# Generated by Django 4.0.4 on 2022-07-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0037_item_imports_num_prints_item_imports_print_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('manager_phone', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('manager_mail', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
