# Generated by Django 4.0.4 on 2022-07-31 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0038_manger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_imports',
            name='customer_manager',
        ),
        migrations.RemoveField(
            model_name='order_imports',
            name='customer_manager_mail',
        ),
        migrations.RemoveField(
            model_name='order_imports',
            name='customer_manager_phone',
        ),
        migrations.AddField(
            model_name='order_imports',
            name='manager',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.manger'),
        ),
    ]
