# Generated by Django 4.0.4 on 2022-08-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0039_remove_order_imports_customer_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_imports',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
