# Generated by Django 4.0.4 on 2022-09-03 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0041_makety_print_in_maket_item_in_maket_item_in_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemgroup_in_Maket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.detail_set')),
                ('maket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.makety')),
            ],
        ),
        migrations.AddField(
            model_name='print_in_maket',
            name='checked',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Item_in_Maket',
        ),
    ]
