# Generated by Django 4.0.4 on 2022-09-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0042_itemgroup_in_maket_print_in_maket_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makety',
            name='order_num',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
