# Generated by Django 4.0.4 on 2022-09-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0046_remove_order_imports_film_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_imports',
            name='date_num',
        ),
    ]
