# Generated by Django 4.0.4 on 2022-09-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0050_print_group_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='print_in_maket',
            name='option',
            field=models.SmallIntegerField(default=1),
        ),
    ]
