# Generated by Django 4.0.4 on 2022-09-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0052_remove_films_item_group_itemgroup_in_maket_film_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
