# Generated by Django 4.0.4 on 2022-09-12 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0053_films_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup_in_maket',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.item_imports'),
        ),
    ]
