# Generated by Django 4.0.4 on 2022-09-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0054_alter_itemgroup_in_maket_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print_group',
            name='code',
            field=models.CharField(default=0, max_length=7),
        ),
    ]
