# Generated by Django 4.0.4 on 2022-09-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0056_films_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='film_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='films',
            name='film_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_imports',
            name='order_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order_imports',
            name='order_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='makety',
            name='maket_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
