# Generated by Django 4.0.4 on 2022-09-18 22:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0058_alter_order_imports_order_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_imports',
            name='order_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='files/orders'), upload_to=''),
        ),
    ]
