# Generated by Django 4.0.4 on 2022-09-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0060_alter_films_film_file_alter_makety_maket_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_imports',
            name='to_check',
            field=models.BooleanField(default=False),
        ),
    ]
