# Generated by Django 4.0.4 on 2022-10-07 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0061_order_imports_to_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup_in_maket',
            name='maket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maket.makety'),
        ),
        migrations.AlterField(
            model_name='print_in_maket',
            name='maket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maket.makety'),
        ),
    ]
