# Generated by Django 4.0.4 on 2022-10-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0064_alter_makety_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_item_print',
        ),
    ]
