# Generated by Django 4.0.4 on 2022-10-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0065_delete_order_item_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print_imports',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
