# Generated by Django 4.0.4 on 2022-10-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0066_alter_print_imports_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_imports',
            name='customer_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
