# Generated by Django 4.0.4 on 2022-10-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0067_alter_order_imports_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_set',
            name='detail6_name',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='detail_set',
            name='detail6_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item_imports',
            name='detail1_hex',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='item_imports',
            name='detail2_hex',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='item_imports',
            name='detail3_hex',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='item_imports',
            name='detail4_hex',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='item_imports',
            name='detail5_hex',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='item_imports',
            name='detail6_color',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item_imports',
            name='detail6_hex',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
    ]
