# Generated by Django 4.0.4 on 2022-10-31 16:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0068_detail_set_detail6_name_detail_set_detail6_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='print_group',
            name='pattern_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='files/patterns'), upload_to=''),
        ),
    ]
