# Generated by Django 4.0.4 on 2022-10-31 20:25

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0069_print_group_pattern_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='files/additional'), upload_to='')),
                ('additional_file_name', models.FilePathField(max_length=120)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maket.order_imports')),
            ],
        ),
    ]
