# Generated by Django 4.0.4 on 2022-11-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0070_additional_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional_files',
            name='file_type',
            field=models.CharField(blank=True, default='pdf', max_length=3, null=True),
        ),
    ]
