# Generated by Django 4.0.4 on 2022-11-02 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0072_remove_print_position_position_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='print_imports',
            name='print_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.print_place'),
        ),
    ]
