# Generated by Django 4.0.4 on 2022-11-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0074_print_imports_print_position_print_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print_color',
            name='color_number_in_item',
            field=models.SmallIntegerField(default=1),
        ),
    ]
