# Generated by Django 4.0.4 on 2022-11-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0075_alter_print_color_color_number_in_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print_color',
            name='color_pantone',
            field=models.CharField(default='', max_length=40),
        ),
    ]
