# Generated by Django 4.0.4 on 2022-11-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0076_alter_print_color_color_pantone'),
    ]

    operations = [
        migrations.AddField(
            model_name='print_group',
            name='item_height',
            field=models.DecimalField(decimal_places=3, default=39, max_digits=7),
        ),
        migrations.AddField(
            model_name='print_group',
            name='item_width',
            field=models.DecimalField(decimal_places=3, default=39, max_digits=7),
        ),
    ]
