# Generated by Django 4.0.4 on 2022-11-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0077_print_group_item_height_print_group_item_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='print_group',
            name='item_height_initial',
            field=models.DecimalField(decimal_places=3, default=39, max_digits=7),
        ),
        migrations.AddField(
            model_name='print_group',
            name='item_width_initial',
            field=models.DecimalField(decimal_places=3, default=39, max_digits=7),
        ),
    ]
