# Generated by Django 4.0.4 on 2022-11-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0078_print_group_item_height_initial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_imports',
            name='number_additional',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_imports',
            name='number_makets',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_imports',
            name='number_orders',
            field=models.SmallIntegerField(default=0),
        ),
    ]
