# Generated by Django 4.0.4 on 2022-12-10 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0079_order_imports_number_additional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Good_crm_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Good_matrix_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_name', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='detail_set',
            name='eco',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Customer_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.customer_types')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.customer_groups'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.customer_types'),
        ),
        migrations.AddField(
            model_name='detail_set',
            name='crm',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.good_crm_type'),
        ),
        migrations.AddField(
            model_name='detail_set',
            name='matrix',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.good_matrix_type'),
        ),
    ]
