# Generated by Django 4.0.4 on 2022-12-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0080_customer_types_good_crm_type_good_matrix_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='frigat_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
