# Generated by Django 4.0.4 on 2022-12-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0081_customer_frigat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_types',
            name='group_discount',
            field=models.SmallIntegerField(default=0),
        ),
    ]
