# Generated by Django 4.0.4 on 2022-12-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0082_customer_types_group_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_types',
            name='group_discount',
            field=models.FloatField(default=0),
        ),
    ]
