# Generated by Django 4.0.4 on 2022-12-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0084_customer_types_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_first',
            field=models.DateField(default='2018-01-01'),
        ),
    ]
