# Generated by Django 4.0.4 on 2023-01-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0086_customer_all_customer_customer_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_first',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='customer_all',
            name='date_import',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
