# Generated by Django 4.0.4 on 2023-01-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0087_alter_customer_date_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_groups',
            name='mail',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customer_groups',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
