# Generated by Django 4.0.4 on 2023-01-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0088_customer_groups_mail_customer_groups_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_last',
            field=models.DateField(default='2100-01-01'),
        ),
    ]
