# Generated by Django 4.0.4 on 2023-01-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0090_alter_customer_all_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
