# Generated by Django 4.0.4 on 2023-01-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0092_customer_groups_date_first_customer_groups_date_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_groups',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
