# Generated by Django 4.0.4 on 2023-01-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0093_customer_groups_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_imports',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
