# Generated by Django 4.0.4 on 2023-01-17 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0094_alter_item_imports_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_set',
            name='print_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maket.print_group'),
        ),
    ]
