# Generated by Django 4.0.4 on 2023-01-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0095_alter_detail_set_print_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='group',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='customer_all',
            name='group',
        ),
        migrations.RemoveField(
            model_name='customer_all',
            name='type',
        ),
    ]
