# Generated by Django 4.0.4 on 2023-02-25 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0096_remove_customer_group_remove_customer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='active',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_first',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_last',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='frigat_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='internal',
        ),
        migrations.AddField(
            model_name='customer_all',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer_all',
            name='date_first',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='customer_all',
            name='date_last',
            field=models.DateField(default=datetime.date(2100, 1, 1)),
        ),
        migrations.AddField(
            model_name='customer_all',
            name='internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer_all',
            name='date_import',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
