# Generated by Django 4.0.4 on 2023-02-25 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0097_remove_customer_active_remove_customer_date_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_all',
            name='date_last',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
