# Generated by Django 4.0.4 on 2023-03-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0100_alter_customer_groups_date_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_groups',
            name='mail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer_groups',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
