# Generated by Django 4.0.4 on 2023-03-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0101_alter_customer_groups_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_all',
            name='frigat_id',
            field=models.CharField(db_index=True, default='', max_length=30),
        ),
    ]
